### ISSUE TITLE
[Feat-FE] CharacterSheet Page

### ISSUE THREAD

**Issue by sook000** [sixtale-trpg/lab-repository#106]
In GitLab by @Remnant1318 on Aug 15, 2024, 03:48

## 📔 Description
- 캐릭터 시트 페이지 

## 🐈 Todo

- [ ] 아래쪽 비디오 프로필영역 => 더미데이터 치우고 실제 유저 데이터 불러오기
- [ ] GM section => 실제 gm 정보 불러오기, 
- [ ] 그 외 나머지 수정
- [ ] 토큰 구별 하기

**Comment by sook000** [comment]
In GitLab by @Remnant1318 on Aug 15, 2024, 03:49

created branch [`106-feat-fe-charactersheet-page`](/s11-webmobile1-sub2/S11P12D108/-/compare/master...106-feat-fe-charactersheet-page) to address this issue
