### ISSUE TITLE
[Feat-BE] Map API

### ISSUE THREAD

**Issue by sook000** [sixtale-trpg/lab-repository#20]
In GitLab by @jjsshhhhh on Jul 25, 2024, 09:29

## 📔 Description
- Map API 구현

## 🐈 Todo

- [x] 맵 목록 불러오기
- [x] 맵 정보 불러오기
- [x] 장소 이동 이벤트 목록 불러오기
- [x] 장소 이동 이벤트 불러오기
- [x] NPC 정보 이벤트 목록 불러오기
- [x] NPC 정보 이벤트 불러오기

**Comment by sook000** [comment]
In GitLab by @jjsshhhhh on Jul 25, 2024, 17:35

mentioned in commit 027c75f0ebe56a263b77a438d3648955af842f8c

**Comment by sook000** [comment]
In GitLab by @jjsshhhhh on Jul 26, 2024, 24:07

created branch [`20-feat-be-map-api`](/s11-webmobile1-sub2/S11P12D108/-/compare/master...20-feat-be-map-api) to address this issue

**Comment by sook000** [comment]
In GitLab by @jjsshhhhh on Jul 26, 2024, 24:23

marked the checklist item **NPC 정보 이벤트 목록 불러오기** as completed

**Comment by sook000** [comment]
In GitLab by @jjsshhhhh on Jul 26, 2024, 24:23

marked the checklist item **장소 이동 이벤트 목록 불러오기** as completed

**Comment by sook000** [comment]
In GitLab by @jjsshhhhh on Jul 26, 2024, 24:38

mentioned in commit cd89c0e29932cfe1c85e9e445ade5f6a72f2418a

**Comment by sook000** [comment]
In GitLab by @jjsshhhhh on Jul 26, 2024, 01:27

created branch [`20-feat-be-map-api`](/s11-webmobile1-sub2/S11P12D108/-/compare/master...20-feat-be-map-api) to address this issue

**Comment by sook000** [comment]
In GitLab by @jjsshhhhh on Jul 26, 2024, 01:49

mentioned in commit d033c3415ebbf995e07e027d086c5bd076cc6f93

**Comment by sook000** [comment]
In GitLab by @jjsshhhhh on Jul 26, 2024, 09:04

marked the checklist item **NPC 정보 이벤트 불러오기** as completed

**Comment by sook000** [comment]
In GitLab by @jjsshhhhh on Jul 26, 2024, 09:04

marked the checklist item **장소 이동 이벤트 불러오기** as completed
