### ISSUE TITLE
[Feat-BE] Room info API

### ISSUE THREAD

**Issue by sook000** [sixtale-trpg/lab-repository#21]
## 📔 Description
- 게임 방 입장과 관련한 api
- 게임 방 생성
- 게임 방 정보 조회(입장한 후)
- 게임 방 정보 수정(입장한 후)
- 게임 방 목록 조회
- 게임 방 입장시 체크
- 게임 방 안의 입장한 회원 일정 전체 조회

## 🐈 Todo

- [x] 게임 방 생성
- [x] 게임 방 정보 조회
- [x] 게임 방 정보 수정
- [x] 게임 방 목록 조회
- [x] 게임 방 입장 시 비밀번호 체크
- [x] 게임 방 입장, 퇴장 ======> 확인 필요, 가끔 에러남

**Comment by sook000** [comment]
created branch [`21-feat-be-room-info-api`](/s11-webmobile1-sub2/S11P12D108/-/compare/master...21-feat-be-room-info-api) to address this issue

**Comment by sook000** [comment]
created branch [`21-feat-be-room-info-api`](/s11-webmobile1-sub2/S11P12D108/-/compare/master...21-feat-be-room-info-api) to address this issue

**Comment by sook000** [comment]
created branch [`21-feat-be-room-info-api`](/s11-webmobile1-sub2/S11P12D108/-/compare/master...21-feat-be-room-info-api) to address this issue

**Comment by sook000** [comment]
created branch [`21-feat-be-room-info-api`](/s11-webmobile1-sub2/S11P12D108/-/compare/master...21-feat-be-room-info-api) to address this issue

**Comment by sook000** [comment]
mentioned in commit d5537947c0e3921c1983e72bb5d8864ff60a27bf

**Comment by sook000** [comment]
created branch [`21-feat-be-room-info-api`](/s11-webmobile1-sub2/S11P12D108/-/compare/master...21-feat-be-room-info-api) to address this issue

**Comment by sook000** [comment]
mentioned in commit 09b108b5057cdc60d2bf01fc58845d8128c1d3bf

**Comment by sook000** [comment]
mentioned in commit 18f087d77da00deea428cb5f8a55c152270581a3

**Comment by sook000** [comment]
mentioned in commit d5bebd82f17582182f58a8e5fa574a746c462633

**Comment by sook000** [comment]
mentioned in commit 79e9b9a83dc6c0ea248ca6e05b72948b5657b715

**Comment by sook000** [comment]
created branch [`21-feat-be-room-info-api`](/s11-webmobile1-sub2/S11P12D108/-/compare/master...21-feat-be-room-info-api) to address this issue

**Comment by sook000** [comment]
created branch [`21-feat-be-room-info-api-2`](/s11-webmobile1-sub2/S11P12D108/-/compare/master...21-feat-be-room-info-api-2) to address this issue

**Comment by sook000** [comment]
created branch [`21-feat-be-room-info-api`](/s11-webmobile1-sub2/S11P12D108/-/compare/master...21-feat-be-room-info-api) to address this issue

**Comment by sook000** [comment]
marked the checklist item **게임 방 생성** as completed

**Comment by sook000** [comment]
marked the checklist item **게임 방 정보 조회** as completed

**Comment by sook000** [comment]
marked the checklist item **게임 방 정보 수정** as completed

**Comment by sook000** [comment]
marked the checklist item **게임 방 목록 조회** as completed

**Comment by sook000** [comment]
marked the checklist item **게임 방 입장시 체크** as completed

**Comment by sook000** [comment]
marked the checklist item **게임 방 입장, 퇴장 ======> 확인 필요, 가끔 에러남** as completed

**Comment by sook000** [comment]
created branch [`21-feat-be-room-info-api`](/s11-webmobile1-sub2/S11P12D108/-/compare/master...21-feat-be-room-info-api) to address this issue

**Comment by sook000** [comment]
created branch [`21-feat-be-room-info-api`](/s11-webmobile1-sub2/S11P12D108/-/compare/master...21-feat-be-room-info-api) to address this issue

**Comment by sook000** [comment]
created branch [`21-feat-be-room-info-api`](/s11-webmobile1-sub2/S11P12D108/-/compare/master...21-feat-be-room-info-api) to address this issue

**Comment by sook000** [comment]
mentioned in commit 9916fde48995872565cffe12fd4ddce2b5b0d4af

**Comment by sook000** [comment]
mentioned in commit ded693fc0f012bd7f183c2ac1c5d3d1be3f996e8
