### ISSUE TITLE
[Feat-FE] CharacterInfo Modal

### ISSUE THREAD

**Issue by sook000** [sixtale-trpg/lab-repository#42]
In GitLab by @Remnant1318 on Jul 30, 2024, 24:34

## 📔 Description
- 캐릭터 인포 모달 추가 : 프로필 영역이 너무 작아서 
GM의 조정이 해당 영역에서 어려운 관계로 따로 모달창으로 빼서 구현하기로 함 

## 🐈 Todo

- [ ] 캐릭터 인포 모달창 만들기
- [ ] 플레이어와 GM구분 - 다른 정보들 
- [ ] 미리 axios 요청문 짜두기

**Comment by sook000** [comment]
In GitLab by @Remnant1318 on Aug 9, 2024, 01:12

mentioned in commit 9530e3dbb2fea32db9d3fb958859c589bb00ded3

**Comment by sook000** [comment]
In GitLab by @Remnant1318 on Nov 26, 2024, 14:21

mentioned in commit 319ab4f582a687e1452c47fa7b2c73fc24c02cfa
