### ISSUE TITLE
[Feat-FE] Main Page

### ISSUE THREAD

**Issue by sook000** [sixtale-trpg/lab-repository#70]
In GitLab by @nkyungm on Aug 8, 2024, 14:08

## 📔 Description
- 메인 페이지 프론트 페이지 개발
- 메인 페이지에 들어갈 영상 찾기

## 🐈 Todo

- [ ] 메인 페이지 프론트 개발
- [ ] 시나리오별 gif 영상 제작
- [x] 메인 영상 제작

**Comment by sook000** [comment]
In GitLab by @nkyungm on Aug 8, 2024, 14:09

created branch [`70-feat-fe-main-page`](/s11-webmobile1-sub2/S11P12D108/-/compare/master...70-feat-fe-main-page) to address this issue

**Comment by sook000** [comment]
In GitLab by @nkyungm on Aug 8, 2024, 17:55

mentioned in commit a098c258b5f1875bfd8a2104c2ef545043b4cd13

**Comment by sook000** [comment]
In GitLab by @nkyungm on Aug 10, 2024, 02:04

mentioned in commit 46a927cb2bd434164fe68a4a1406b79cac94353b

**Comment by sook000** [comment]
In GitLab by @nkyungm on Aug 10, 2024, 07:36

mentioned in commit c9b889adafe59ca3614cc69974bf24239bb93d54

**Comment by sook000** [comment]
In GitLab by @nkyungm on Aug 12, 2024, 05:43

marked the checklist item **메인 영상 제작** as completed

**Comment by sook000** [comment]
In GitLab by @nkyungm on Aug 12, 2024, 05:43

created branch [`70-feat-fe-main-page`](/s11-webmobile1-sub2/S11P12D108/-/compare/master...70-feat-fe-main-page) to address this issue

**Comment by sook000** [comment]
In GitLab by @nkyungm on Nov 26, 2024, 14:21

mentioned in commit 8afb015fa94ba5eec27b6dc9ba8b0986e0a69d17

**Comment by sook000** [comment]
In GitLab by @nkyungm on Nov 26, 2024, 14:21

mentioned in commit 6cdab1ca4599c34c1ac5fcef4f2fdd034d9f1040

**Comment by sook000** [comment]
In GitLab by @nkyungm on Nov 26, 2024, 14:21

mentioned in commit 2d54f94150e9407563534532d92c7098b98f4da1
