### ISSUE TITLE
[Feat-FE] Character Sheet

### ISSUE THREAD

**Issue by sook000** [sixtale-trpg/lab-repository#90]
In GitLab by @Remnant1318 on Aug 12, 2024, 14:12

## 📔 Description
- 캐릭터 시트 작성

## 🐈 Todo

- [ ] 캐릭터 시트 로직 작성
- [ ] 캐릭터 시트 api 연동
- [ ] 캐릭터 시트 디자인 수정

**Comment by sook000** [comment]
In GitLab by @Remnant1318 on Aug 12, 2024, 14:12

created branch [`90-feat-fe-character-sheet`](/s11-webmobile1-sub2/S11P12D108/-/compare/master...90-feat-fe-character-sheet) to address this issue
